# Generated by Django 5.1.2 on 2024-12-07 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0002_customer_created_at_alter_customer_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={
                "permissions": [("can_login_kyc_agent", "Can log in as KYC Agent")]
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="registered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The agent who registered this customer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registered_customers",
                to="kyc.agent",
            ),
        ),
    ]
