# Generated by Django 5.1.2 on 2024-12-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0003_alter_agent_options_customer_registered_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveField(
            model_name="customer",
            name="registered_by",
        ),
    ]
