# Generated by Django 5.1.2 on 2024-12-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0004_alter_agent_options_remove_customer_registered_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={"verbose_name": "Agent", "verbose_name_plural": "Agents"},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Customer", "verbose_name_plural": "Customers"},
        ),
    ]
